services:
  generation_service:
    image: generation_service:latest
    build:
      context: ./generation_service
    ports:
      - "9000:9000"
    volumes:
      - ./generation_service:/app
    env_file:
      - .env

  stockage_service:
    image: stockage_service:latest
    build:
      context: ./stockage_service
    ports:
      - "8081:8081"
    env_file:
      - .env

  vue_front_service:
    image: vue_front_service:latest
    build:
      context: ./front_service
    ports:
      - "8080:8080"
    volumes:
      - ./front_service:/app
    env_file:
      - .env
  web:
    build:
      context: ./user_service 
      dockerfile: Dockerfile 
    ports:
      - "5000:5000"
    volumes:
      - ./user_service:/app 
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:postgres@db/user_service 
      command: /bin/bash -c "/app/install.sh && poetry run uvicorn run:asgi_app --host 0.0.0.0 --port 5000"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: user_service
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: on-failure
    healthcheck:
      test: pg_isready -U postgres
volumes:
  postgres_data:
