services:
  # web:
  #   build: .
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - .:/app
  #   command: flask run --host=0.0.0.0 --port=8000
  #   depends_on:
  #     - db

  # db:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_USER: alexiane
  #     POSTGRES_PASSWORD: alexiane
  #     # POSTGRES_PASSWORD: ${DB_PASSWORD}
  #     POSTGRES_DB: user_service
  #   ports:
  #     - "5432:5432"

  generation_service:
    image: generation_service:latest
    build:
      context: ./generation_service
    ports:
      - "9000:9000"
    volumes:
      - ./generation_service:/app
    env_file:
      - .env

  stockage_service:
    image: stockage_service:latest
    build:
      context: ./stockage_service
    ports:
      - "8081:8081"
    env_file:
      - .env

  vue_front_service:
    image: vue_front_service:latest
    build:
      context: ./front_service
    ports:
      - "8080:8080"
    volumes:
      - ./front_service:/app
    env_file:
      - .env