version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0 --port=8000
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: alexiane
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: user_service
    ports:
      - "5432:5432"
