name: Renov-Design CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install

      - name: Install Sphinx and Extensions
        run: |
          poetry add sphinx sphinx_autodoc_typehints

      # Uncomment the following steps if needed
      # - name: Lint with flake8
      #   run: |
      #     poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      #     poetry run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      # - name: Test with pytest
      #   run: |
      #     poetry run pytest

      # - name: Deploy Docs
      # - name: Build Docker Images
      # - name: Push Docker Images
      # - name: Deploy App
